// The messages generated by the API are strings for variants with no data and
// {[variant]: {...data}} for others. This doesn't work well with Typescript's
// exhaustiveness, so convert messages into a tagged union type
const convertApiUnion = (apiUnion: any): any => {
  if (typeof apiUnion === 'string') {
    return {type: apiUnion} as any;
  } else {
    const keys = Object.keys(apiUnion);
    if (keys.length !== 1) {
      throw new Error('Unexpected message from API');
    } else {
      const key = keys[0];
      return {
        type: key,
        ...apiUnion[key],
      };
    }
  }
};

export default convertApiUnion;
